"""Initial migration

Revision ID: 05b4d8a7a6e2
Revises: 
Create Date: 2025-07-21 11:39:57.178322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b4d8a7a6e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jpeg_preview_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('jpeg_preview_url')

    # ### end Alembic commands ###
