"""empty message

Revision ID: 06fb95b32d16
Revises: 9f52ffec62c9
Create Date: 2025-06-13 11:43:13.485507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fb95b32d16'
down_revision = '9f52ffec62c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('patient_id', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=280),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['patient_id'])
        batch_op.create_unique_constraint(None, ['national_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('patient_id')
        batch_op.drop_column('national_id')

    op.drop_table('users')
    # ### end Alembic commands ###
