"""baseline schema

Revision ID: 130ff5d7ead8
Revises: 
Create Date: 2025-08-04 19:20:33.558727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130ff5d7ead8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mch_number', sa.String(length=80), nullable=True))
        batch_op.drop_constraint(batch_op.f('patient_national_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_patient_mch_number'), ['mch_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_patient_national_id'), ['national_id'], unique=True)

    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jpeg_preview_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('jpeg_preview_url')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_national_id'))
        batch_op.drop_index(batch_op.f('ix_patient_mch_number'))
        batch_op.create_unique_constraint(batch_op.f('patient_national_id_key'), ['national_id'])
        batch_op.drop_column('mch_number')

    # ### end Alembic commands ###
