"""Add Sext to Patient

Revision ID: 2527ca930783
Revises: 967ffcebc648
Create Date: 2025-06-24 12:23:04.816650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2527ca930783'
down_revision = '967ffcebc648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.String(length=20), nullable=True))

    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
