"""new columns added patient_name, modality, studY_date

Revision ID: 3815f6075e13
Revises: 2527ca930783
Create Date: 2025-06-26 10:52:15.945725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3815f6075e13'
down_revision = '2527ca930783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modality', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('study_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('patient_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('patient_name')
        batch_op.drop_column('study_date')
        batch_op.drop_column('modality')

    # ### end Alembic commands ###
