"""add external_id to patient

Revision ID: 967ffcebc648
Revises: c78f73f1c22e
Create Date: 2025-06-17 14:21:15.037110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967ffcebc648'
down_revision = 'c78f73f1c22e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=True))
        batch_op.drop_constraint(batch_op.f('patient_patient_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['external_id'])
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('patient_patient_id_key'), ['patient_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
