"""Add timestamp to Scan

Revision ID: c1df0739261f
Revises: 05b4d8a7a6e2
Create Date: 2025-07-27 22:38:25.540699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1df0739261f'
down_revision = '05b4d8a7a6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
